CC=gcc
CFLAGS = -g -Wall -o

all: Assg1


Assg1: Assg1.c
	$(CC) Assg1.c SchedSim.o -o Assg1

ule: ule.c
	$(CC) ule.c SchedSim.o -o ule

4BSD: 4BSD.c
	$(CC) 4BSD.c SchedSim.o -o 4BSD

clean:
	rm Assg1 ule 4BSD
